import { sql } from "drizzle-orm";
import { db, ensureDatabase, sqlite } from "@/lib/db";
import { assertEditionWorkRelation, createCatalogEdition as createCatalogEditionInAdapter, createCatalogOwnedCopy, loadWorksForEditions, type CatalogOwnedCopyInput } from "@/lib/db/catalog-adapter";
import { uid } from "@/lib/utils";
import type { Annotation, BookEdition, Category, Concept, Loan, OwnedCopy, ResearchFolder, ResearchWork, ShelfLocation, Tag, WishlistItem } from "@/lib/types";

const USER_ID = "local-owner";
const parse = <T>(value: unknown, fallback: T): T => { try { return value ? JSON.parse(String(value)) as T : fallback; } catch { return fallback; } };

export function listOwnedCopies(includeDeleted = false) {
  ensureDatabase();
  const deletedFilter = includeDeleted ? sql`` : sql`AND c.deleted_at IS NULL`;
  const records = db.all(sql`SELECT c.*, e.title, e.authors, e.translators, e.publisher, e.publication_year, e.edition, e.original_title, e.series_name, e.edition_statement, e.edition_number, e.print_run, e.publication_date, e.edition_notes, e.original_publisher, e.format, e.language, e.isbn10, e.isbn13, e.pages, e.description, e.cover_url, e.subjects, e.source, e.external_id FROM owned_copies c JOIN book_editions e ON e.id = c.edition_id WHERE c.user_id = ${USER_ID} ${deletedFilter} ORDER BY c.created_at DESC`) as Array<Record<string, unknown>>;
  const works = loadWorksForEditions(records.map((record) => String(record.edition_id)));
  return records.map((record) => toOwnedCopy(record, works.get(String(record.edition_id))));
}

export function getOwnedCopy(id: string) {
  ensureDatabase();
  const record = db.get(sql`SELECT c.*, e.title, e.authors, e.translators, e.publisher, e.publication_year, e.edition, e.original_title, e.series_name, e.edition_statement, e.edition_number, e.print_run, e.publication_date, e.edition_notes, e.original_publisher, e.format, e.language, e.isbn10, e.isbn13, e.pages, e.description, e.cover_url, e.subjects, e.source, e.external_id FROM owned_copies c JOIN book_editions e ON e.id = c.edition_id WHERE c.id = ${id} AND c.user_id = ${USER_ID}`) as Record<string, unknown> | undefined;
  const works = record ? loadWorksForEditions([String(record.edition_id)]) : new Map();
  return record ? toOwnedCopy(record, works.get(String(record.edition_id))) : null;
}

function toOwnedCopy(record: Record<string, unknown>, work?: import("@/lib/types").Work): OwnedCopy {
  const category = record.category_id ? db.get(sql`SELECT id,name,description,color FROM categories WHERE id = ${record.category_id}`) as Category | undefined : undefined;
  const tags = db.all(sql`SELECT t.id,t.name,t.color FROM tags t JOIN copy_tags ct ON ct.tag_id=t.id WHERE ct.copy_id=${record.id}`) as Tag[];
  const edition: BookEdition = { id: String(record.edition_id), title: String(record.title), authors: parse<string[]>(record.authors, []), translators: parse<string[]>(record.translators, []), publisher: record.publisher ? String(record.publisher) : undefined, publicationYear: record.publication_year ? Number(record.publication_year) : undefined, edition: record.edition ? String(record.edition) : undefined, originalTitle: record.original_title ? String(record.original_title) : undefined, seriesName: record.series_name ? String(record.series_name) : undefined, editionStatement: record.edition_statement ? String(record.edition_statement) : undefined, editionNumber: record.edition_number ? Number(record.edition_number) : undefined, printRun: record.print_run ? Number(record.print_run) : undefined, publicationDate: record.publication_date ? String(record.publication_date) : undefined, editionNotes: record.edition_notes ? String(record.edition_notes) : undefined, originalPublisher: record.original_publisher ? String(record.original_publisher) : undefined, format: record.format ? String(record.format) : undefined, language: record.language ? String(record.language) : undefined, isbn10: record.isbn10 ? String(record.isbn10) : undefined, isbn13: record.isbn13 ? String(record.isbn13) : undefined, pages: record.pages ? Number(record.pages) : undefined, description: record.description ? String(record.description) : undefined, coverUrl: record.cover_url ? String(record.cover_url) : undefined, subjects: parse<string[]>(record.subjects, []), source: String(record.source), externalId: record.external_id ? String(record.external_id) : undefined, workId: work?.id };
  return { id: String(record.id), userId: String(record.user_id), editionId: String(record.edition_id), edition, work, location: record.location ? String(record.location) : undefined, shelfLocationId: record.shelf_location_id ? String(record.shelf_location_id) : undefined, shelfSlot: record.shelf_slot ? String(record.shelf_slot) : undefined, shelfCoordinate: record.shelf_coordinate ? String(record.shelf_coordinate) : undefined, locationSortOrder: record.location_sort_order === null || record.location_sort_order === undefined ? undefined : Number(record.location_sort_order), category, tags, readingStatus: String(record.reading_status) as OwnedCopy["readingStatus"], rating: record.rating === null || record.rating === undefined ? undefined : Number(record.rating), notes: record.notes ? String(record.notes) : undefined, acquiredAt: record.acquired_at ? String(record.acquired_at) : undefined, acquisitionMethod: record.acquisition_method ? String(record.acquisition_method) as OwnedCopy["acquisitionMethod"] : undefined, acquisitionSource: record.acquisition_source ? String(record.acquisition_source) : undefined, acquisitionPlace: record.acquisition_place ? String(record.acquisition_place) : undefined, priceCents: record.price_cents === null || record.price_cents === undefined ? undefined : Number(record.price_cents), currency: record.currency ? String(record.currency) : undefined, condition: record.condition ? String(record.condition) : undefined, inscription: record.inscription ? String(record.inscription) : undefined, receiptNote: record.receipt_note ? String(record.receipt_note) : undefined, createdAt: String(record.created_at), updatedAt: String(record.updated_at), deletedAt: record.deleted_at ? String(record.deleted_at) : null };
}

export function createOwnedCopy(input: CatalogOwnedCopyInput) {
  return createCatalogOwnedCopy(input);
}

export function updateOwnedCopy(id: string, input: Record<string, unknown>) {
  ensureDatabase();
  const current = getOwnedCopy(id); if (!current) return null;
  const value = <T>(key: string, fallback: T) => input[key] !== undefined ? input[key] as T : fallback;
  const nullable = (value: unknown) => value === "" ? null : value;
  db.run(sql`UPDATE owned_copies SET location=${nullable(value("location", current.location ?? null)) as string | null}, category_id=${nullable(value("categoryId", current.category?.id ?? null)) as string | null}, reading_status=${value("readingStatus", current.readingStatus) as string}, rating=${nullable(value("rating", current.rating ?? null)) as number | null}, notes=${nullable(value("notes", current.notes ?? null)) as string | null}, acquired_at=${nullable(value("acquiredAt", current.acquiredAt ?? null)) as string | null}, acquisition_method=${nullable(value("acquisitionMethod", current.acquisitionMethod ?? null)) as string | null}, acquisition_source=${nullable(value("acquisitionSource", current.acquisitionSource ?? null)) as string | null}, acquisition_place=${nullable(value("acquisitionPlace", current.acquisitionPlace ?? null)) as string | null}, price_cents=${nullable(value("priceCents", current.priceCents ?? null)) as number | null}, currency=${nullable(value("currency", current.currency ?? null)) as string | null}, condition=${nullable(value("condition", current.condition ?? null)) as string | null}, inscription=${nullable(value("inscription", current.inscription ?? null)) as string | null}, receipt_note=${nullable(value("receiptNote", current.receiptNote ?? null)) as string | null}, shelf_location_id=${nullable(value("shelfLocationId", current.shelfLocationId ?? null)) as string | null}, shelf_slot=${nullable(value("shelfSlot", current.shelfSlot ?? null)) as string | null}, shelf_coordinate=${nullable(value("shelfCoordinate", current.shelfCoordinate ?? null)) as string | null}, location_sort_order=${nullable(value("locationSortOrder", current.locationSortOrder ?? null)) as number | null}, updated_at=${new Date().toISOString()} WHERE id=${id} AND user_id=${USER_ID}`);
  return getOwnedCopy(id);
}

export function updateBookEdition(id: string, input: Record<string, unknown>) {
  ensureDatabase();
  assertEditionWorkRelation(id);
  const current = db.get(sql`SELECT id FROM book_editions WHERE id=${id}`);
  if (!current) return null;
  const value = <T>(key: string, fallback: T) => input[key] !== undefined ? input[key] as T : fallback;
  const record = db.get(sql`SELECT * FROM book_editions WHERE id=${id}`) as Record<string, unknown>;
  db.run(sql`UPDATE book_editions SET title=${value("title", String(record.title))}, authors=${JSON.stringify(value("authors", parse<string[]>(record.authors, [])))}, translators=${JSON.stringify(value("translators", parse<string[]>(record.translators, [])))}, publisher=${value("publisher", record.publisher as string | null)}, publication_year=${value("publicationYear", record.publication_year as number | null)}, edition=${value("edition", record.edition as string | null)}, original_title=${value("originalTitle", record.original_title as string | null)}, series_name=${value("seriesName", record.series_name as string | null)}, edition_statement=${value("editionStatement", record.edition_statement as string | null)}, edition_number=${value("editionNumber", record.edition_number as number | null)}, print_run=${value("printRun", record.print_run as number | null)}, publication_date=${value("publicationDate", record.publication_date as string | null)}, edition_notes=${value("editionNotes", record.edition_notes as string | null)}, original_publisher=${value("originalPublisher", record.original_publisher as string | null)}, format=${value("format", record.format as string | null)}, language=${value("language", record.language as string | null)}, isbn10=${value("isbn10", record.isbn10 as string | null)}, isbn13=${value("isbn13", record.isbn13 as string | null)}, pages=${value("pages", record.pages as number | null)}, description=${value("description", record.description as string | null)}, cover_url=${value("coverUrl", record.cover_url as string | null)}, subjects=${JSON.stringify(value("subjects", parse<string[]>(record.subjects, [])))}, source=${value("source", String(record.source))}, external_id=${value("externalId", record.external_id as string | null)} WHERE id=${id}`);
  return db.get(sql`SELECT id FROM book_editions WHERE id=${id}`);
}

export function updateCatalogBook(id: string, input: { edition?: Record<string, unknown>; copy?: Record<string, unknown> }) {
  ensureDatabase();
  const current = getOwnedCopy(id);
  if (!current) return null;
  const write = sqlite.transaction(() => {
    if (input.edition) updateBookEdition(current.editionId, input.edition);
    if (input.copy) updateOwnedCopy(id, input.copy);
  });
  write();
  return getOwnedCopy(id);
}

export function softDeleteOwnedCopy(id: string) { ensureDatabase(); db.run(sql`UPDATE owned_copies SET deleted_at=${new Date().toISOString()}, updated_at=${new Date().toISOString()} WHERE id=${id} AND user_id=${USER_ID}`); return getOwnedCopy(id); }
export function restoreOwnedCopy(id: string) { ensureDatabase(); db.run(sql`UPDATE owned_copies SET deleted_at=NULL, updated_at=${new Date().toISOString()} WHERE id=${id} AND user_id=${USER_ID}`); return getOwnedCopy(id); }

export function listCategories() { ensureDatabase(); return db.all(sql`SELECT id,name,description,color FROM categories WHERE user_id=${USER_ID} ORDER BY name`) as Category[]; }
export function createCategory(input: { name: string; description?: string; color?: string }) { ensureDatabase(); const id = uid(); db.run(sql`INSERT INTO categories (id,name,description,color,user_id) VALUES (${id},${input.name},${input.description ?? null},${input.color ?? "navy"},${USER_ID})`); return db.get(sql`SELECT id,name,description,color FROM categories WHERE id=${id}`) as Category; }
export function listTags() { ensureDatabase(); return db.all(sql`SELECT id,name,color FROM tags WHERE user_id=${USER_ID} ORDER BY name`) as Tag[]; }
export function listShelves(includeInactive = false) { ensureDatabase(); const activeFilter = includeInactive ? sql`` : sql`AND active=1`; const records = db.all(sql`SELECT id,name,parent_id as parentId,room,sort_order as sortOrder,active FROM shelf_locations WHERE user_id=${USER_ID} ${activeFilter} ORDER BY sort_order,name`) as Array<Record<string, unknown>>; return records.map((shelf) => ({ id: String(shelf.id), name: String(shelf.name), parentId: shelf.parentId ? String(shelf.parentId) : null, room: shelf.room ? String(shelf.room) : undefined, sortOrder: Number(shelf.sortOrder ?? 0), active: Boolean(shelf.active) })) as ShelfLocation[]; }
export function createShelf(input: { name: string; parentId?: string; room?: string }) { ensureDatabase(); const id = uid(); const order = (db.get(sql`SELECT COALESCE(MAX(sort_order), -1) + 1 as nextOrder FROM shelf_locations WHERE user_id=${USER_ID}`) as { nextOrder: number }).nextOrder; db.run(sql`INSERT INTO shelf_locations (id,name,parent_id,room,user_id,sort_order,active) VALUES (${id},${input.name},${input.parentId ?? null},${input.room ?? ""},${USER_ID},${order},1)`); return listShelves(true).find((shelf) => shelf.id === id) as ShelfLocation; }
export function updateShelf(id: string, input: { name?: string; parentId?: string | null; room?: string; sortOrder?: number; active?: boolean }) { ensureDatabase(); const current = listShelves(true).find((shelf) => shelf.id === id); if (!current) return null; db.run(sql`UPDATE shelf_locations SET name=${input.name ?? current.name}, parent_id=${input.parentId === undefined ? current.parentId ?? null : input.parentId}, room=${input.room ?? current.room ?? null}, sort_order=${input.sortOrder ?? current.sortOrder}, active=${input.active === undefined ? (current.active ? 1 : 0) : (input.active ? 1 : 0)} WHERE id=${id} AND user_id=${USER_ID}`); return listShelves(true).find((shelf) => shelf.id === id) ?? null; }
export function shelfUsage(id: string) { ensureDatabase(); return (db.get(sql`SELECT count(*) as count FROM owned_copies WHERE shelf_location_id=${id} AND user_id=${USER_ID} AND deleted_at IS NULL`) as { count: number }).count; }
export function deleteShelf(id: string) { ensureDatabase(); if (!listShelves(true).some((shelf) => shelf.id === id)) return { ok: false as const, reason: "NOT_FOUND" as const }; if (shelfUsage(id) > 0) return { ok: false as const, reason: "IN_USE" as const }; db.run(sql`DELETE FROM shelf_locations WHERE id=${id} AND user_id=${USER_ID}`); return { ok: true as const }; }

function toLoan(record: Record<string, unknown>): Loan {
  const dueAt = record.due_at ? String(record.due_at) : undefined;
  return { id: String(record.id), copyId: String(record.copy_id), borrowerName: String(record.borrower_name), borrowerContact: record.borrower_contact ? String(record.borrower_contact) : undefined, lentAt: String(record.lent_at), dueAt, returnedAt: record.returned_at ? String(record.returned_at) : undefined, status: String(record.status) as Loan["status"], overdue: String(record.status) === "active" && dueAt !== undefined && dueAt < new Date().toISOString().slice(0, 10), note: record.note ? String(record.note) : undefined };
}
export function listLoans(copyId: string) { ensureDatabase(); return (db.all(sql`SELECT * FROM loans WHERE copy_id=${copyId} ORDER BY lent_at DESC`) as Array<Record<string, unknown>>).map(toLoan); }
export function createLoan(copyId: string, input: { borrowerName: string; borrowerContact?: string; dueAt?: string; note?: string }) { ensureDatabase(); if (!getOwnedCopy(copyId)) return { ok: false as const, reason: "NOT_FOUND" as const }; const active = db.get(sql`SELECT id FROM loans WHERE copy_id=${copyId} AND status='active' LIMIT 1`); if (active) return { ok: false as const, reason: "ALREADY_LENT" as const }; const id = uid(); db.run(sql`INSERT INTO loans (id,copy_id,borrower_name,borrower_contact,lent_at,due_at,status,note) VALUES (${id},${copyId},${input.borrowerName},${input.borrowerContact ?? null},${new Date().toISOString()},${input.dueAt ?? null},'active',${input.note ?? null})`); return { ok: true as const, loan: toLoan(db.get(sql`SELECT * FROM loans WHERE id=${id}`) as Record<string, unknown>) }; }
export function returnLoan(id: string) { ensureDatabase(); const current = db.get(sql`SELECT * FROM loans WHERE id=${id}`) as Record<string, unknown> | undefined; if (!current) return null; db.run(sql`UPDATE loans SET status='returned', returned_at=${new Date().toISOString()} WHERE id=${id} AND status='active'`); return toLoan(db.get(sql`SELECT * FROM loans WHERE id=${id}`) as Record<string, unknown>); }
export function renewLoan(id: string, dueAt: string) { ensureDatabase(); const current = db.get(sql`SELECT * FROM loans WHERE id=${id} AND status='active'`); if (!current) return null; db.run(sql`UPDATE loans SET due_at=${dueAt} WHERE id=${id} AND status='active'`); return toLoan(db.get(sql`SELECT * FROM loans WHERE id=${id}`) as Record<string, unknown>); }

function annotationConcepts(annotationId: string) { return db.all(sql`SELECT c.id,c.name,c.description FROM concepts c JOIN annotation_concepts ac ON ac.concept_id=c.id WHERE ac.annotation_id=${annotationId} ORDER BY c.name`) as Concept[]; }
function toAnnotation(record: Record<string, unknown>): Annotation { return { id: String(record.id), copyId: String(record.copy_id), pageLabel: record.page_label ? String(record.page_label) : undefined, body: String(record.body), createdAt: String(record.created_at), updatedAt: String(record.updated_at), concepts: annotationConcepts(String(record.id)) }; }
export function listAnnotations(copyId?: string, conceptName?: string) { ensureDatabase(); const where = copyId ? sql`WHERE a.copy_id=${copyId}` : conceptName ? sql`JOIN annotation_concepts ac_filter ON ac_filter.annotation_id=a.id JOIN concepts c_filter ON c_filter.id=ac_filter.concept_id WHERE lower(c_filter.name)=lower(${conceptName})` : sql``; const records = db.all(sql`SELECT DISTINCT a.* FROM annotations a ${where} ORDER BY a.created_at DESC`) as Array<Record<string, unknown>>; return records.map(toAnnotation); }
export function createAnnotation(copyId: string, input: { pageLabel?: string; body: string; concepts?: string[] }) { ensureDatabase(); if (!getOwnedCopy(copyId)) return null; const id = uid(); const now = new Date().toISOString(); db.run(sql`INSERT INTO annotations (id,copy_id,page_label,body,created_at,updated_at) VALUES (${id},${copyId},${input.pageLabel ?? null},${input.body},${now},${now})`); setAnnotationConcepts(id, input.concepts ?? []); return toAnnotation(db.get(sql`SELECT * FROM annotations WHERE id=${id}`) as Record<string, unknown>); }
export function updateAnnotation(id: string, input: { pageLabel?: string | null; body?: string; concepts?: string[] }) { ensureDatabase(); const current = db.get(sql`SELECT * FROM annotations WHERE id=${id}`) as Record<string, unknown> | undefined; if (!current) return null; db.run(sql`UPDATE annotations SET page_label=${input.pageLabel === undefined ? current.page_label as string | null : input.pageLabel}, body=${input.body ?? String(current.body)}, updated_at=${new Date().toISOString()} WHERE id=${id}`); if (input.concepts) setAnnotationConcepts(id, input.concepts); return toAnnotation(db.get(sql`SELECT * FROM annotations WHERE id=${id}`) as Record<string, unknown>); }
export function deleteAnnotation(id: string) { ensureDatabase(); db.run(sql`DELETE FROM annotation_concepts WHERE annotation_id=${id}`); db.run(sql`DELETE FROM annotations WHERE id=${id}`); }
function setAnnotationConcepts(annotationId: string, names: string[]) { db.run(sql`DELETE FROM annotation_concepts WHERE annotation_id=${annotationId}`); for (const rawName of names) { const name = rawName.trim().slice(0, 80); if (!name) continue; let concept = db.get(sql`SELECT id FROM concepts WHERE user_id=${USER_ID} AND lower(name)=lower(${name})`) as { id: string } | undefined; if (!concept) { const id = uid(); db.run(sql`INSERT INTO concepts (id,name,user_id) VALUES (${id},${name},${USER_ID})`); concept = { id }; } db.run(sql`INSERT OR IGNORE INTO annotation_concepts (annotation_id,concept_id) VALUES (${annotationId},${concept.id})`); } }

export function listWishlist() { ensureDatabase(); const records = db.all(sql`SELECT w.id AS wishlist_id,w.note,w.created_at,e.id AS edition_id,e.title,e.authors,e.publisher,e.publication_year,e.format,e.language,e.isbn13,e.cover_url,e.source FROM wishlist_items w JOIN book_editions e ON e.id=w.edition_id WHERE w.user_id=${USER_ID} ORDER BY w.created_at DESC`) as Array<Record<string, unknown>>; const works = loadWorksForEditions(records.map((record) => String(record.edition_id))); return records.map((record) => ({ id: String(record.wishlist_id), note: record.note ? String(record.note) : undefined, createdAt: String(record.created_at), edition: { id: String(record.edition_id), title: String(record.title), authors: parse<string[]>(record.authors, []), publisher: record.publisher ? String(record.publisher) : undefined, publicationYear: record.publication_year ? Number(record.publication_year) : undefined, format: record.format ? String(record.format) : undefined, language: record.language ? String(record.language) : undefined, isbn13: record.isbn13 ? String(record.isbn13) : undefined, coverUrl: record.cover_url ? String(record.cover_url) : undefined, source: String(record.source), workId: works.get(String(record.edition_id))?.id } })) as WishlistItem[]; }
export function addWishlist(edition: BookEdition, note?: string) { ensureDatabase(); const existing = edition.isbn13 ? db.get(sql`SELECT w.id FROM wishlist_items w JOIN book_editions e ON e.id=w.edition_id WHERE e.isbn13=${edition.isbn13} AND w.user_id=${USER_ID}`) : null; if (existing) return existing; const { editionId } = createCatalogEditionInAdapter(edition); const id = uid(); db.run(sql`INSERT INTO wishlist_items (id,edition_id,note,user_id,created_at) VALUES (${id},${editionId},${note ?? null},${USER_ID},${new Date().toISOString()})`); return { id }; }
export function removeWishlist(id: string) { ensureDatabase(); db.run(sql`DELETE FROM wishlist_items WHERE id=${id} AND user_id=${USER_ID}`); }

export function listResearch() { ensureDatabase(); const folders = db.all(sql`SELECT f.id,f.name,f.description,f.created_at,count(fw.work_id) as workCount FROM research_folders f LEFT JOIN folder_works fw ON fw.folder_id=f.id WHERE f.user_id=${USER_ID} GROUP BY f.id ORDER BY f.created_at DESC`) as Array<Record<string, unknown>>; const works = db.all(sql`SELECT * FROM research_works WHERE user_id=${USER_ID} ORDER BY created_at DESC`) as Array<Record<string, unknown>>; return { folders: folders.map((f) => ({ id: String(f.id), name: String(f.name), description: f.description ? String(f.description) : undefined, workCount: Number(f.workCount) })) as ResearchFolder[], works: works.map(toResearchWork) }; }
function toResearchWork(work: Record<string, unknown>): ResearchWork { const folderIds = db.all(sql`SELECT folder_id as id FROM folder_works WHERE work_id=${work.id}`).map((x) => String((x as { id: unknown }).id)); return { id: String(work.id), title: String(work.title), authors: parse<string[]>(work.authors, []), abstract: work.abstract ? String(work.abstract) : undefined, doi: work.doi ? String(work.doi) : undefined, journal: work.journal ? String(work.journal) : undefined, year: work.year ? Number(work.year) : undefined, tags: parse<string[]>(work.tags, []), notes: work.notes ? String(work.notes) : undefined, openAccessUrl: work.open_access_url ? String(work.open_access_url) : undefined, source: work.source ? String(work.source) : undefined, folderIds }; }
export function createResearchWork(input: Omit<ResearchWork, "id" | "folderIds"> & { folderId?: string }) { ensureDatabase(); const id = uid(); const now = new Date().toISOString(); db.run(sql`INSERT INTO research_works (id,title,authors,abstract,doi,journal,year,tags,notes,open_access_url,source,user_id,created_at) VALUES (${id},${input.title},${JSON.stringify(input.authors)},${input.abstract ?? null},${input.doi ?? null},${input.journal ?? null},${input.year ?? null},${JSON.stringify(input.tags)},${input.notes ?? null},${input.openAccessUrl ?? null},${input.source ?? "local"},${USER_ID},${now})`); if (input.folderId) db.run(sql`INSERT OR IGNORE INTO folder_works (folder_id,work_id) VALUES (${input.folderId},${id})`); return id; }
export function createResearchFolder(input: { name: string; description?: string }) { ensureDatabase(); const id = uid(); db.run(sql`INSERT INTO research_folders (id,name,description,user_id,created_at) VALUES (${id},${input.name},${input.description ?? null},${USER_ID},${new Date().toISOString()})`); return { id }; }

export function exportData() { ensureDatabase(); return { version: 1, exportedAt: new Date().toISOString(), userId: USER_ID, books: listOwnedCopies(true), categories: listCategories(), tags: listTags(), shelves: listShelves(), wishlist: listWishlist(), research: listResearch() }; }
