import { brand } from "@/lib/brand";

export const messages = {
  zh: {
    app: { name: brand.nameZh, tagline: "为每一本书，留下清晰的位置" },
    nav: { home: "首页", library: "藏书", addBook: "添加图书", search: "检索", wishlist: "心愿单", research: "论文资料夹", manage: "分类与位置", settings: "设置", groups: { library: "藏书", discovery: "发现", manage: "管理" } },
    common: { search: "搜索", loading: "加载中", empty: "这里还没有内容", save: "保存", cancel: "取消", confirm: "确认", delete: "删除", edit: "编辑", add: "添加", back: "返回", all: "全部", viewAll: "查看全部", close: "关闭", retry: "重试", source: "来源", language: "语言", zh: "中文", en: "English", noCover: "暂无封面", success: "已完成", failed: "操作失败", optional: "可选", select: "选择", manage: "管理", openMenu: "打开菜单", primaryNavigation: "主导航", mobileNavigation: "移动导航", skipToContent: "跳到主要内容" },
    welcome: { eyebrow: "一个安静的藏书入口", title: brand.mottoZh, subtitle: "把纸质书、书架位置与论文线索放在同一条可回看的路径里。进入藏书室，再慢慢补全每一本书的故事。", enter: "进入我的藏书室", skipNext: "下次直接进入", visualLabel: "抽象的书架与书脊图形", visualNote: "纸上有痕，架上有序", footer: "本地优先 · 你的藏书由你掌握" },
    home: { eyebrow: "我的藏书室", title: "我的藏书", subtitle: "添加、查找并整理每一本书。", addBook: "添加一本书", searchLibrary: "检索图书与文献", statsLabel: "藏书统计", statsBooks: "藏书总量", statsReading: "正在阅读", statsUnread: "待读", statsPapers: "论文资料", statsDetail: "当前本地记录", recent: "最近入藏", shelves: "书架一览", emptyRecent: "还没有最近入藏的书", emptyRecentHint: "从一本书开始建立你的藏书秩序。", noShelves: "还没有书架位置", noShelvesHint: "先创建第一个位置，之后就能在首页看到它的藏书数量。", createShelf: "创建第一个位置", shelfBooks: "本书", localMode: "本地数据", statusLine: "本地数据已就绪" },
    library: { title: "我的藏书", subtitle: "把每一本实体书，放回它应该在的位置。", searchPlaceholder: "搜索书名、作者、ISBN…", grid: "网格", list: "列表", filter: "筛选", status: "阅读状态", category: "分类", location: "位置", sort: "排序", newest: "最近入藏", titleSort: "书名", rating: "评分", selected: "已选择", move: "移动", archive: "移入回收站", restore: "恢复", noResults: "没有找到匹配的藏书", clear: "清除筛选" },
    add: { title: "添加图书", subtitle: "先找到准确版本，再把它放进你的书架。", byTitle: "按书名添加", byIsbn: "扫描 / ISBN", manual: "完全手动录入", titlePlaceholder: "输入书名，例如：百年孤独", isbnPlaceholder: "输入 ISBN-10 或 ISBN-13", find: "查找书目", searching: "正在检索书目…", titleHint: "输入完整书名；结果来自公开书目，也可以随时手动录入。", scanning: "扫描功能即将支持", scanHint: "目前可以手动输入 ISBN；若没有匹配结果，仍可手动录入。", versions: "选择具体版本", versionsHint: "确认出版社、年份和装帧后再加入藏书。", confirmVersion: "确认此版本", otherVersions: "其他版本", confidence: "匹配度", noMatch: "暂未找到匹配书目", noMatchHint: "请核对书名、作者或 ISBN；一个字的差异也可能影响匹配。", unavailable: "书目服务暂时不可用。可以重试，也可以直接切换到手动录入。", useManual: "带入手动录入", manualTitle: "书名", manualAuthors: "作者", manualPublisher: "出版社", manualYear: "出版年份", manualIsbn: "ISBN-13", manualLanguage: "语言", manualFormat: "装帧", manualPages: "页数", manualDescription: "简介", manualLocation: "书架位置", manualCategory: "分类", manualStatus: "阅读状态", created: "已加入藏书", duplicate: "这个 ISBN 已有一本", addAnother: "新增另一册", openExisting: "打开已有记录" },
    search: { title: "统一检索", subtitle: "在书目和论文之间，找到下一条线索。", placeholder: "搜索书名、作者、主题、DOI…", books: "图书", papers: "论文", searchHint: "试试搜索“设计”“人工智能”或一个 DOI", addWishlist: "加入心愿单", savedWishlist: "已在心愿单", savePaper: "保存到资料夹", savedPaper: "已保存", related: "相关内容", noResults: "没有找到结果", offline: "暂时没有可用的联网结果，请检查网络后重试。", sourceGoogle: "Google Books", sourceOpenLibrary: "Open Library", sourceCrossref: "Crossref", paperAbstract: "摘要" },
    wishlist: { title: "心愿单", subtitle: "留住还没遇见、但想带回家的书。", empty: "心愿单还是空的", emptyHint: "在统一检索中把心动的书保存下来。", remove: "移除" },
    research: { title: "论文资料夹", subtitle: "把论文线索整理成可回看的研究路径。", newFolder: "新建资料夹", empty: "还没有资料夹", open: "打开", folderName: "资料夹名称", folderPrompt: "为论文建立一个可回看的主题空间。", folderEmptyHint: "先建立一个主题空间，之后保存的论文会集中在这里。", worksEmptyHint: "先在左侧创建资料夹，再从检索结果中保存论文。", notes: "个人备注", openAccess: "开放获取原文", doi: "DOI", journal: "期刊", year: "年份" },
    manage: { title: "分类与位置", subtitle: "让纸质书的层级位置，也能被快速找到。", categories: "自定义分类", tags: "标签", tagsHint: "给跨分类的书标记主题、阅读场景或项目；输入名称后点击右侧加号。", shelves: "层级书架", newCategory: "新建分类", newShelf: "新建位置", categoryPlaceholder: "例如：设计与方法", shelfPlaceholder: "例如：补充位置说明", deleteHint: "删除前请先移动仍在使用的藏书。", focusShelf: "新建第一个位置" },
    settings: { title: "设置", subtitle: "数据、语言与品牌入口都在这里。", appearance: "界面语言", languageHint: "选择你更习惯的阅读语言。", data: "数据与备份", exportJson: "导出 JSON", exportCsv: "导出 CSV", importCsv: "导入 CSV", backupHint: "导出的文件可以用于备份或迁移到未来的云端版本。", local: "本地电脑模式", localHint: "藏书管理无需登录，数据保存于本机 SQLite。", entry: "进入页", entryHint: "随时查看品牌入口；藏书与资料仍保存在本机。", viewEntry: "查看进入页", resetEntry: "恢复进入页" },
    import: { title: "导入藏书", subtitle: "先预览 CSV，再把可识别的记录加入本地藏书。", csvLabel: "CSV 内容", placeholder: "title,authors,isbn13\n百年孤独,加西亚·马尔克斯,9787544253994", preview: "预览", commit: "导入已通过的记录", empty: "还没有预览数据", success: "已导入记录", invalid: "请先粘贴 CSV 内容。" },
    status: { unread: "未读", reading: "在读", read: "已读", paused: "暂停", dropped: "弃读" },
  },
  en: {
    app: { name: brand.nameEn, tagline: "Give every book a clear place" },
    nav: { home: "Home", library: "Library", addBook: "Add book", search: "Search", wishlist: "Wishlist", research: "Research folders", manage: "Categories & shelves", settings: "Settings", groups: { library: "Library", discovery: "Discover", manage: "Manage" } },
    common: { search: "Search", loading: "Loading", empty: "Nothing here yet", save: "Save", cancel: "Cancel", confirm: "Confirm", delete: "Delete", edit: "Edit", add: "Add", back: "Back", all: "All", viewAll: "View all", close: "Close", retry: "Retry", source: "Source", language: "Language", zh: "中文", en: "English", noCover: "No cover", success: "Done", failed: "Action failed", optional: "Optional", select: "Select", manage: "Manage", openMenu: "Open menu", primaryNavigation: "Primary navigation", mobileNavigation: "Mobile navigation", skipToContent: "Skip to content" },
    welcome: { eyebrow: "A quiet entrance to your library", title: brand.mottoEn, subtitle: "Keep physical books, shelf locations, and research trails in one path you can return to. Enter your library and fill in the details at your own pace.", enter: "Enter my library", skipNext: "Enter directly next time", visualLabel: "Abstract shelf and book spine illustration", visualNote: "Stories on paper, order on the shelf", footer: "Local first · Your collection stays yours" },
    home: { eyebrow: "MY LIBRARY", title: "My books", subtitle: "Add, find, and keep every book in order.", addBook: "Add a book", searchLibrary: "Search books & papers", statsLabel: "Library statistics", statsBooks: "Books owned", statsReading: "Reading", statsUnread: "To read", statsPapers: "Research papers", statsDetail: "Current local records", recent: "Recently added", shelves: "Shelf overview", emptyRecent: "No recently added books", emptyRecentHint: "Start with one book and build your library order from there.", noShelves: "No shelf locations yet", noShelvesHint: "Create the first location and its book count will appear here.", createShelf: "Create first location", shelfBooks: "books", localMode: "Local data", statusLine: "Local data is ready" },
    library: { title: "My library", subtitle: "Put every physical book back where it belongs.", searchPlaceholder: "Search title, author, ISBN…", grid: "Grid", list: "List", filter: "Filters", status: "Reading status", category: "Category", location: "Location", sort: "Sort", newest: "Recently added", titleSort: "Title", rating: "Rating", selected: "selected", move: "Move", archive: "Move to recycle bin", restore: "Restore", noResults: "No books match your filters", clear: "Clear filters" },
    add: { title: "Add a book", subtitle: "Find the exact edition before it joins your shelf.", byTitle: "By title", byIsbn: "Scan / ISBN", manual: "Manual entry", titlePlaceholder: "Enter a title, e.g. One Hundred Years of Solitude", isbnPlaceholder: "Enter ISBN-10 or ISBN-13", find: "Find book", searching: "Searching book catalogs…", titleHint: "Enter the complete title. Results come from public catalogs, and manual entry is always available.", scanning: "Scanning support is coming soon", scanHint: "For now, enter an ISBN manually; you can still add a book manually when no result is found.", versions: "Choose an edition", versionsHint: "Confirm publisher, year, and format before adding it.", confirmVersion: "Confirm this edition", otherVersions: "Other editions", confidence: "Match", noMatch: "No matching catalog record yet", noMatchHint: "Check the title, author, or ISBN. A one-character difference can affect matching.", unavailable: "The catalog service is unavailable. Retry, or switch to manual entry.", useManual: "Use in manual form", manualTitle: "Title", manualAuthors: "Authors", manualPublisher: "Publisher", manualYear: "Publication year", manualIsbn: "ISBN-13", manualLanguage: "Language", manualFormat: "Format", manualPages: "Pages", manualDescription: "Description", manualLocation: "Shelf location", manualCategory: "Category", manualStatus: "Reading status", created: "Added to library", duplicate: "This ISBN is already owned", addAnother: "Add another copy", openExisting: "Open existing record" },
    search: { title: "Unified search", subtitle: "Find the next thread between books and papers.", placeholder: "Search title, author, topic, DOI…", books: "Books", papers: "Papers", searchHint: "Try “design”, “artificial intelligence”, or a DOI", addWishlist: "Add to wishlist", savedWishlist: "On wishlist", savePaper: "Save to folder", savedPaper: "Saved", related: "Related", noResults: "No results found", offline: "No network results are available right now. Check your connection and try again.", sourceGoogle: "Google Books", sourceOpenLibrary: "Open Library", sourceCrossref: "Crossref", paperAbstract: "Abstract" },
    wishlist: { title: "Wishlist", subtitle: "Keep the books you have not met yet, but want to bring home.", empty: "Your wishlist is empty", emptyHint: "Save a book from unified search to keep it here.", remove: "Remove" },
    research: { title: "Research folders", subtitle: "Turn paper trails into a research path you can revisit.", newFolder: "New folder", empty: "No folders yet", open: "Open", folderName: "Folder name", folderPrompt: "Create a calm topic space for papers you want to revisit.", folderEmptyHint: "Create a topic space first; saved papers will collect here.", worksEmptyHint: "Create a folder on the left, then save papers from search results.", notes: "Personal notes", openAccess: "Open access", doi: "DOI", journal: "Journal", year: "Year" },
    manage: { title: "Categories & shelves", subtitle: "Make the hierarchy of your physical shelves searchable.", categories: "Custom categories", tags: "Tags", tagsHint: "Mark books by topic, reading context, or project; enter a name and press the plus button.", shelves: "Shelf hierarchy", newCategory: "New category", newShelf: "New location", categoryPlaceholder: "e.g. Design & methods", shelfPlaceholder: "e.g. Study / Cabinet A / Shelf 2", deleteHint: "Move books still using this item before deleting it.", focusShelf: "Create your first location" },
    settings: { title: "Settings", subtitle: "Data, language, and the brand entry live here.", appearance: "Interface language", languageHint: "Choose the language you prefer to read in.", data: "Data & backup", exportJson: "Export JSON", exportCsv: "Export CSV", importCsv: "Import CSV", backupHint: "Exports work as backups and can migrate into a future cloud version.", local: "Local computer mode", localHint: "Library management works without sign-in and stores data in local SQLite.", entry: "Entry page", entryHint: "Open the brand entry page any time; your library stays on this computer.", viewEntry: "View entry page", resetEntry: "Restore entry page" },
    import: { title: "Import books", subtitle: "Preview a CSV first, then add valid rows to your local library.", csvLabel: "CSV content", placeholder: "title,authors,isbn13\nOne Hundred Years of Solitude,Gabriel García Márquez,9787544253994", preview: "Preview", commit: "Import valid rows", empty: "No preview yet", success: "records imported", invalid: "Paste CSV content first." },
    status: { unread: "Unread", reading: "Reading", read: "Read", paused: "Paused", dropped: "Dropped" },
  },
} as const;

export type MessageSchema = typeof messages.zh;

